services:
  backend:
    container_name: sdm-backend-container
    image: back-img
    restart: always
    ports:
      - "8000:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vertex-ai-access-key.json
    volumes:
      - /studymate-backend/studymate-backend/tmp/keys/vertex-ai-access-key.json:/app/vertex-ai-access-key.json:ro
    networks:
      - backend-network

networks:
  backend-network:
    external: true
