services:
  backend:
    container_name: sdm-backend-container
    image: back-img
    restart: always
    ports:
      - "8000:8080"
    env_file:
      - /home/admin-preprod/backend-env/.env
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    #   - DB_SERVER=${DB_SERVER}
    #   - DB_NAME=${DB_NAME}
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    #   - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    volumes:
      - ./studymate-backend/tmp/keys/vertex-ai-access-key.json:/app/vertex-ai-access-key.json:ro
    networks:
      - backend-network
    labels:
      traefik.enable: "true"
      traefik.http.services.sdm-backend.loadbalancer.server.port: "8080"
      traefik.http.services.sdm-backend.loadbalancer.server.scheme: "http"
      traefik.http.routers.sdm-backend-https.entrypoints: "websecure"
      traefik.http.routers.sdm-backend-https.rule: "Host(`preprod.backend.savvystudymate.com`) || Host(`backend.savvystudymate.com`)"
      traefik.http.routers.sdm-backend-https.tls: "true"
      traefik.http.routers.sdm-backend-https.tls.certresolver: "cloudflare"

networks:
  backend-network:
    external: true
  frontend-network:
    external: true
