services:
  backend:
    container_name: sdm-backend-prod-container
    image: backend-prod-img
    restart: always
    ports:
      - "8000:8080"
    env_file:
      - /home/CE67-27/backend/.env
    networks:
      - prod-network

networks:
  prod-network:
    external: true
