FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

WORKDIR /app

EXPOSE 5000

ENV ASPNETCORE_URLS=http://*:5000
ENV ASPNETCORE_ENVIRONMENT=dev

COPY ["studymate-backend.sln", "./"]
COPY ["studymate-backend/studymate-backend.csproj", "./studymate-backend/"]
COPY ["studymate-backend-tests/studymate-backend-tests.csproj", "./studymate-backend-tests/"]

RUN dotnet restore .

COPY . .

ENTRYPOINT ["dotnet", "watch", "run", "--project", "studymate-backend"]