# Unique project key
sonar.projectKey=kmitl-savvy-students_studymate-backend_944fc207-7ea9-446a-ace5-ef3f9905d4ac

# Project name and version
sonar.projectName=studymate-backend
sonar.projectVersion=1.0

# Base directory of the project
sonar.projectBaseDir=./

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Test directories
sonar.tests=Tests

# Exclusions to prevent analyzing build artifacts
sonar.exclusions=**/obj/**,**/bin/**

# Optionally, include only specific file types
sonar.inclusions=**/*.cs
sonar.test.inclusions=Tests/**/*.cs